### ISSUE TITLE
Fix (or remove) crypto handling

### ISSUE THREAD

**Issue by tylerknott** [greyspots/envelope#2]
The current state of your use of cryptography is pretty bad.  I saw on the Hacker News thread that you changed the way you were initializing your crypto keys but it is still not correct.

1. The C standard library rand() function is *not* cryptographically secure and should *never* be used to generate cryptographic keys.  Ever!  In fact the way you are using it is not even recommended in non-cryptographic contexts since some widely-used implementations of it have less randomness in their lower bits of output so using modulus actually significantly decreases the already poor security of it.
2. You are already linking against OpenSSL, why not just use its built-in cryptographic RNG?
3. You are treating the keys as strings when they are not.  They are an opaque sequence of bytes. There is no requirement for them to be valid ASCII characters and by limiting them to ASCII characters you are reducing the key strength from 256 bits to about 208 bits.

I was actually working on a pull request to fix the above when I realized the following were also broken:

2. Why are using OpenSSL's private AES functions instead of the public [EVP_Encrypt\*](https://www.openssl.org/docs/manmaster/crypto/EVP_EncryptInit.html) interface?
3. There is no message authentication. This means the user could change the ciphertext and your program would be operating on garbage without any knowledge.  I suggest using OpenSSL's HMAC with the SHA256 hash (in Encrypt-then-MAC mode, i.e. you generate the MAC on the ciphertext after encryption and validate it before decryption) using a separate key for the HMAC (i.e. do not re-use the AES key or IV).
4. Why do you have an option to use hardcoded keys? It looks like the intent of that option is to allow you to prevent users from being logged out each day at midnight (when the AES key regenerates and their cookies become invalidated) but that should not mean you use a hardcoded key, it should just mean that you never regenerate the key after the first time it is generated.  If you need to know the key for debugging purposes have a block of code (guarded by a \#ifdef so the code can never be hit in production) that prints out the key.
1. Why are the keys in non-static global variables? They're only used within the util_aes.c file so they should just be static globals within that file.  Ditto for the set_aes_key_iv() function.  (This isn't necessarily broken but it's a pretty strong code smell regarding how well code is modularized.)

I'm sorry I don't have a pull request for you but fixing all this is too much effort for something I'm not planning to personally use.

I would actually suggest just getting rid of all of your crypto and using an opaque session key with the actual session data being stored in-memory or in a database on the server itself.  That way you don't need to worry about this kind of stuff (well, aside from using a secure RNG to generate your random session keys so they can't be predicted).

**Comment by justintocci** [comment]
in reply to your list 1, 2 and 3:
Actually, all three of these are just one patch. We now use RAND_bytes()...thank you...fixed

in reply to your list 1,2,3 and 4
1) There is more than one interface. Joseph remembers he chose that one because that was what he found first. He didn't know about the EVP interface. The one we chose works with libressl and openssl. You don't give a reason we need to change it. Without a reason I can't authorize resources.
2) You are correct that messages are not authenticated. We don't understand why this is beneficial. Only the cookie content is encrypted and its always sent over SSL. Please elaborate in case we do need to fix it.
3) Overnight is not an issue. The issue is upgrade of binary while users are logged in. This is a critical development feature that we can't remove. It defaults to run in production mode. Due to your feedback we will be reworking this feature. Look for it Monday. 
4) non-static globals...fixed...thank you

No worries on a pull request. you were very helpful and we are grateful of your contribution. 

We have never seriously discussed session keys because we wanted to have zero footprint in the  database. This way people can try Envelope and if they don't like it we didn't litter in their database.

**Comment by tylerknott** [comment]
> 1) There is more than one interface. Joseph remembers he chose that one because that was what he found first. He didn't know about the EVP interface. The one we chose works with libressl and openssl. You don't give a reason we need to change it. Without a reason I can't authorize resources.

The reason is that one is a private interface which doesn't have any compatibility guarantees and the other is a public interface with them.  If you are fine with OpenSSL changes potentially breaking your code you ignore that point

> 2) You are correct that messages are not authenticated. We don't understand why this is beneficial. Only the cookie content is encrypted and its always sent over SSL. Please elaborate in case we do need to fix it.

The concern is that without authentication a user could edit the value of the cookie to introduce garbage data into your system (or, if they could guess the AES key, alter the data in a meaningful way).  If the data were authenticated you would be able to detect tampering and reject it.

> We have never seriously discussed session keys because we wanted to have zero footprint in the database. This way people can try Envelope and if they don't like it we didn't litter in their database.

Have you considered using a second file-based database like BDB or SQLite for session management?

**Comment by justintocci** [comment]
> The concern is that without authentication a user could edit the value of the cookie to introduce garbage data into your system (or, if they could guess the AES key, alter the data in a meaningful way). If the data were authenticated you would be able to detect tampering and reject it.

The content of the cookie is the user's PostgreSQL user name and password, so any alteration will result in a failed authentication and the user request will be denied. So in that way the cookie contents are authenticated. Since introducing arbitrary data into the cookie can't introduce garbage data into the system, does that mean we have this covered? 

> Have you considered using a second file-based database like BDB or SQLite for session management?

No we haven't. Envelope is the result of a desire to bring desktop style development to websites. The desktop programs we looked to for inspiration didn't use session keys so we never considered it. Without a compelling reason I can't imagine it ending up on the Envelope roadmap because it would confuse our desktop paradigm. 


We are all new to Github and we have no idea about etiquette. We are very grateful for all your help and we don't want to insult you or anyone else. We've opened three "enhancements" as a result of your participation. I hope that's ok. Please let us know if its a problem.

**Comment by tylerknott** [comment]
I'm not on Github very much either, so I can't answer the etiquette question.  As long as you have fixed the RNG and are aware of the potential dangers of the other aspects of your design I feel like this issue could be closed.
